### ISSUE TITLE
How to perform inference on any other RGB/Depth image pairs other than KITTI/Cityscape?

### ISSUE THREAD

**Issue by MalekWahidi** [morancyc/USNet#6]
I would like some help adapting the code to perform inference on any other images. Could this be done by simply changing the command line arguments for test.py, or do I need to create a new class for my custom data instead of kitti.py? I just need to perform inference given a pair of 1280x720 RGB+Depth images.

**Comment by morancyc** [comment]
I think you had better create a new class for your custom data, because the formats of different datasets are not alike. Furthermore, other than RGB+depth images, the camera intrinsics are needed for calculating SNE (surface normal) in our method. You can refer to  [Kitti_Dataset](https://github.com/morancyc/USNet/blob/main/dataset/kitti.py) for example.
